
node_lines:
- node_line_name: retrieve_node_line
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_ndcg, retrieval_mrr]
      top_k: 3
      modules: # TODO: add at least 2 retrieval modules (https://docs.auto-rag.com/nodes/retrieval/retrieval.html#supported-modules)
        - module_type: TODO
        - module_type: TODO
- node_line_name: post_retrieve_node_line
  nodes:
    - node_type: prompt_maker
      strategy:
        metrics:
          - metric_name: meteor
          - metric_name: rouge
          - metric_name: sem_score
            embedding_model: openai
      modules:
        - module_type: fstring
          prompt: TODO # TODO: add at least 1 prompt (you can make more and let AutoRAG choose the best one) https://docs.auto-rag.com/nodes/prompt_maker/prompt_maker.html#example-config-yaml-file
    - node_type: generator
      strategy:
        metrics:
          - metric_name: meteor
          - metric_name: rouge
          - metric_name: sem_score
            embedding_model: openai
      modules:
        - module_type: openai_llm
          llm: gpt-3.5-turbo-0125 # TODO: test different OpenAI models
          batch: 4
