[project]
name = "autorag-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arxiv>=2.1.3",
    "autorag[parse]>=0.3.13",
    "blinker==1.8.2",
    "ipykernel==5.5.6",
    "ipywidgets-bokeh==1.0.2",
]
